### ISSUE TITLE
Flying PX4 flight stack in POSCTL using snap_cam

### ISSUE THREAD

**Issue by asyounis** [PX4/snap_cam#10]
Hello everyone,

I am trying to get snap_cam working on my snapdragon based platform.
I am able to get snap_cam to build and run (using the ROS instructions) but am unable to enter POSCTL mode in PX4.  Every time I try to enter the POSCTL mode, I get a "REJECTED POSITION CONTROL" error.  From looking around online it seems that the PX4 flight stack needs GPS data to enter POSCTL mode.

My questions are the following: 
    1) Has snap_cam ever been used to control a quadcopter/other snapdragon based platform in flight?
    2) Do I need GPS data for flight with snap_cam controlling the quadcopter?
    2) If I do need GPS data, where are the drivers located for GPS (If there are any), I could not find any?
    3) If the answer to question 1 is yes and the answer to question 2 is no, how do I setup my platform to 
        fly with snap_cam and in POSCTL mode without GPS?

Any help would be greatly appreciated.

Thanks,
Ali

**Comment by julianoes** [comment]
@asyounis Thanks for reporting. This seems to be related to https://github.com/PX4/Firmware/issues/4929. I'm looking into it.

**Comment by julianoes** [comment]
@asyounis can you please test #5058?

**Comment by julianoes** [comment]
Resolved with https://github.com/PX4/Firmware/pull/5058.
