### ISSUE TITLE
Cmake warning：Could not find camera libraries, not building targets that depend on it

### ISSUE THREAD

**Issue by xul4m06qj6** [PX4/snap_cam#11]
The message was written in CMakeLists.txt：59

---

find_library(camera_LIBRARIES NAMES camera PATHS /usr/lib)

if (NOT camera_LIBRARIES)
    message(WARNING "Could not find camera libraries, not building targets that depend on it")
endif()

---

Is the NAMES argument searching for "camera" really the right name? or it should be "libcamera.la"?

Also, the PATH argument searches "/usr/lib", but I can't find any library named "camera" or even close to it under that directory. 

Do I have to install OpenCV all the same even I'm not building with ROS?

**Comment by MaMadDl** [comment]
How did u solved this ?

**Comment by xul4m06qj6** [comment]
Sorry, I am no longer studying this project hence I can't remember the
answer.

2017-02-09 20:40 GMT+08:00 Mohammad Ali Gholami <notifications@github.com>:
