### ISSUE TITLE
"Segmentation Fault" when execute optical_flow on Snapdragon_Flight board

### ISSUE THREAD

**Issue by xul4m06qj6** [PX4/snap_cam#12]
As title

I successfully built an executable "optical_flow" and "adb push" it to a Snapdragon_Flight board running Linaro.

When executed it with "./optical_flow" command, error shows "Segmentation Fault".

I traced the code back to "calib_yaml_interface.h"

The error happens when program runs into "YAML::Node CameraMatrix = node["CameraMatrix"];"

This line of code looks normal to me, and the calibration file is original from here.

What went worng?

**Comment by ndepal** [comment]
Are you compiling the package on the Snapdragon or somewhere else? The provided build methods do not cross compile. You are expected to build on the snapdragon board.

Can you try again by cloning the repo onto your Snapdragon and building there?
