### ISSUE TITLE
snap_cam with roslaunch

### ISSUE THREAD

**Issue by hoseongseo** [PX4/snap_cam#13]
Hi, I have some problem related with executing snap_cam via roslaunch.

I tried to start snap_cam with roslaunch, using following command:
$ roslaunch snap_cam highres.launch.
And also px4 was executing at that moment.

But the terminal says,
"Could not open camera 0."

It seems like snap_cam must be executed by root authority, like 'sudo'. 
But the roslaunch command cannot be executed by 'sudo'.

Is there any solution for my problem?

**Comment by ChristophTobler** [comment]
You have to be root to access the camera
run ```su``` beforehand
