### ISSUE TITLE
How to adjust the Exposure？

### ISSUE THREAD

**Issue by d2h7** [PX4/snap_cam#14]
Hi
   I recently find out the image of  snapcam often become vary dark, and i modify the DEFAULT_EXPOSURE_VALUE but it's useless.
  I would like to know whether there is a way to modify the brightness of the camera?

**Comment by bhairavmehta95** [comment]
I know this issue is old, but would anyone else be able to help us out?

**Comment by ChristophTobler** [comment]
You can adjust the exposure with the `-e` argument. see [here](https://github.com/PX4/snap_cam/blob/87ad6fa81c0ae3cc93ead73f650f2218186845e1/src/SnapCam.cpp#L702-L710)

**Comment by ChristophTobler** [comment]
Ah I think `params_.setManualExposure(cfg.exposureValue);` is missing [here](https://github.com/PX4/snap_cam/blob/87ad6fa81c0ae3cc93ead73f650f2218186845e1/src/SnapCam.cpp#L142)

**Comment by ChristophTobler** [comment]
I tried both cameras and setting `params_.setManualExposure(<exposureValue>);` to a hardcoded value didn't seem to change anything for me...

**Comment by ChristophTobler** [comment]
The exposure can now manually be set with `-e`, e.g. `./optical_flow -e 50`
