### ISSUE TITLE
camera library

### ISSUE THREAD

**Issue by MaMadDl** [PX4/snap_cam#15]
hi when i try to make in ROS i get the following error in configure thus nothing will get made :
"Could not find camera libraries, not building targets that depend on it"

what is camera library and how to install it ?

thanks in advance

**Comment by ChristophTobler** [comment]
@MaMadDl are you compiling on a Snapdragon Flight? Because this camera library should be on there by default.

**Comment by ChristophTobler** [comment]
@MaMadDl Please reopen if it's still an issue
