### ISSUE TITLE
Auto Exposure

### ISSUE THREAD

**Issue by bhairavmehta95** [PX4/snap_cam#17]
I am looking to use my Snapdragon Flight Optical Flow camera with an autoexposure setting, but any time I run the camera driver, my image is always overexposed. 

How can I change this so that my image is no longer overexposed, either through manual settings or setting an auto-exposure setting (if there is one)?

Background: I am trying to run the camera driver outside (Indoors, everything works fine).

**Comment by ChristophTobler** [comment]
There is no auto exposure ATM. But you can set the exposure. see [here](https://github.com/PX4/snap_cam/issues/14)

**Comment by bhairavmehta95** [comment]
To anyone who is looking for this feature, I forked my own branch of the ATLFlight's ros-examples and added an image publisher.

To be clear, I was looking for an autoexposure feature, but also a way to publish images so that other software could be run on the board.

**Comment by ChristophTobler** [comment]
@bhairavmehta95 You can publish the images with ros...
