### ISSUE TITLE
Need for auto exposure

### ISSUE THREAD

**Issue by ChristophTobler** [PX4/snap_cam#18]

**Comment by ChristophTobler** [comment]
@mcharleb FYI

**Comment by ChristophTobler** [comment]
`setManualExposure()` and `setManualGain()` currently don't change anything. The image is always very bright

**Comment by jywilson** [comment]
Christoph,

I am checking on this.  These functions should work for the tracking (downward facing) camera, but not for the 4K camera.  You are asking with regard to the tracking camera, correct?

Jim W.

**Comment by jywilson** [comment]
Christoph,

Can you look this sample code over and see if there is anything you are doing differently?  This demonstrates the use of the functions you are asking about.  

https://source.codeaurora.org/quic/la/platform/hardware/qcom/camera/tree/libcamera/test/camera_test.cpp?h=LNX.LER.1.2

line# 1183

Jim W.

**Comment by ChristophTobler** [comment]
@jywilson Yes, I'm setting it for the downward facing camera. As far as I can see, I do exactly the same as in the example. I added `params_.setManualExposure(1);` and `params_.setManualGain(1);` here https://github.com/PX4/snap_cam/blob/master/src/SnapCam.cpp#L142 and they don't seem to change anything

**Comment by ChristophTobler** [comment]
@jywilson When I change the other parameters like `params_.setPreviewFormat()`, they do change. So I `params_.commit()` is working. I tried using `OnVideoFrame()` and `camera_->startRecording()` instead of `OnPreviewFrame()` and `camera_->startPreview()`, but didn't change anything. I still get a very bright image.

**Comment by ChristophTobler** [comment]
@jywilson I tried on another Snapdragon Flight and the images are also very bright. Weirdly preview was not working on that one and I had to change to `OnVideoFrame()` and `camera_->startRecording()`.

**Comment by jywilson** [comment]
Okay, thanks Christoph for the update!  I will run this on my end and see if we get the same results.

**Comment by rkintada** [comment]
hi @ChristophTobler, the version of libcamera in snap_cam project is a snapshot of the code checked in over a year ago.  I am suspecting if the latest version of the code had fixed this.  Can you update the snap_cam project to use the libcamera code from: https://source.codeaurora.org/quic/la/platform/hardware/qcom/camera/tree/libcamera?h=LNX.LER.1.2

If you can add this as submodule reference it would be great.

Thanks
Rama

**Comment by ChristophTobler** [comment]
Thanks @rkintada, adding it as a submodule would certainly make sense. But I don't think that's the reason it doesn't work, because it does work with the camera test that already is inside snap_cam. I have to check why that is...
And we still need auto exposure. Is there some auto exposure for Snapdragon from Qualcomm?

**Comment by ChristophTobler** [comment]
@jywilson @rkintada https://github.com/PX4/snap_cam/blob/master/src/SnapCam.cpp#L182-L194 this fixed the manual exposure. Weirdly the params need to be commited, then the preview needs to be started and then you can set the exposure and gain...

**Comment by ChristophTobler** [comment]
I added an auto exposure which isn't perfect but gets the job done.
