### ISSUE TITLE
Memory leak when using highres launch file

### ISSUE THREAD

**Issue by marcelinomalmeidan** [PX4/snap_cam#22]
Monitoring the snap_cam process on `top`, the `%MEM` jumps by about 5% every ~2-3 seconds or so. This only happens when using the highres launch file; optflow does not have the same issue.

**Comment by ChristophTobler** [comment]
Thanks for reporting! I'll have a look at it.

**Comment by ChristophTobler** [comment]
@marcelinomalmeidan You are using latest master, right? Because there have been some memory leak fixes.

**Comment by marcelinomalmeidan** [comment]
@ChristophTobler Yes we are. We saw the latest commit addressing the memory leak and we thought that would fix it, but this seems to be a separate issue.

**Comment by ChristophTobler** [comment]
@marcelinomalmeidan Should be fixed in latest master. Can you pull the newest changes and verify?

**Comment by marcelinomalmeidan** [comment]
@ChristophTobler, thank you very much! It works now!
