### ISSUE TITLE
How to capture a raw snapshot with the front camera? 

### ISSUE THREAD

**Issue by TuckerHaydon** [PX4/snap_cam#28]
Sorry, don't know the correct place to post this. 

Is there a way to capture raw snapshots with snap_cam using the front camera? I've noticed that frames are encoded as JPEG when passed as arguments to the onPictureFrame callback function. I'd like to access the uncompressed frames.

**Comment by ChristophTobler** [comment]
According to the "Snapdragon Flight User Guide", raw format is only available for the optic camera

**Comment by TuckerHaydon** [comment]
Thank you!
