### ISSUE TITLE
snap_cam build

### ISSUE THREAD

**Issue by twistxj** [PX4/snap_cam#29]
I'm a bit confused by the instructions.  How do I use the git clone command on the snapdragon?  The instructions aren't very clear in the readme.

**Comment by ChristophTobler** [comment]
What exactly is not clear? You use the `git clone` command just like on any terminal. What does not work?

**Comment by LorenzMeier** [comment]
You need to run the commands and build them on the host, not on the Snapdragon. Start with the instructions on http://dev.px4.io

**Comment by ChristophTobler** [comment]
If you want to build the [Firmware](https://github.com/PX4/Firmware), then yes. The instructions for [snap_cam](https://github.com/PX4/snap_cam#setup), however, have to be run on the Snapdragon Flight. You can get a shell with `adb shell`, if you connect your board via USB.
