### ISSUE TITLE
CameraCalibrator.py uses old Calibration Syntax

### ISSUE THREAD

**Issue by bmundt6** [PX4/snap_cam#30]
Using OpenCV 3, the function cv2.calibrateCamera(...) requires five positional arguments (whereas OpenCV 2 only required the first three). Setting the cameraMatrix and distCoeffs positional parameters to None fixes this.

**Comment by ChristophTobler** [comment]
Thanks for reporting. I'll look into it

**Comment by ChristophTobler** [comment]
Couldn't replicate your issue. I have OpenCV 3.1 and it works just fine. What exactly was your setup/issue?

**Comment by ChristophTobler** [comment]
@bmundt6 feel free to reopen with a more detailed description. Thanks!
