### ISSUE TITLE
Question: Difference between Snapshot, Video, and Preview frames

### ISSUE THREAD

**Issue by TuckerHaydon** [PX4/snap_cam#31]
What exactly is the difference between snapshot, video, and preview frames? The callback functions all take the same data type as a parameter. I'm assuming that it's the way the camera captures the images. Is there any documentation on this?

**Comment by ChristophTobler** [comment]
Not sure if there is a difference for the frames. They just have different settings. Why are you asking?
The only difference I know about preview and video is that the exposure does not work for preview frames.
Unfortunately, I don't know of any documentation.

**Comment by TuckerHaydon** [comment]
I'm using the snapdragon for photogrammetry. The FPS of single snapshots is rather low (~2). Was wondering what the difference between snapshot frames and other frames is and if there is any benefit to using snapshot over the others.

**Comment by ChristophTobler** [comment]
Maybe the settings are different (longer exposure etc.). But just guessing...
@rkintada can you comment?

**Comment by rkintada** [comment]
Both Video and Preview and streaming callback vs Snapshot is only on a request basis.  Before the callbacks are tiggerred one has to set the camera parameters.  These will determine the image that is provided in the callback.  

For Video and Preview, the sensor setting used will be largest of the setting used for the either of the preview or video.  For example if the preview is configured for 720p and the Video is configured for 1080p, then the physical sensor is configured for 1080p and the Camera pipeline will downscale the image to 720p for preview callback.  This is similar for other setting as well( like fps ).  One thing to note for fps is that they can be only in multiples( like 1x or 2x etc ).  So if the camera setting for preview is 30fps and then the video can be 60, 90 or 120fps and limited by the capability of the sensor.  

Hope this helps. 
Thanks

**Comment by TuckerHaydon** [comment]
If I understand this right, other than FPS and resolution--which can be selected--, there is no difference in the type of data or the clarity, crispness, or exposure time between snapshots and video frames.
