### ISSUE TITLE
Libcamera Test File Contradictory 

### ISSUE THREAD

**Issue by TuckerHaydon** [PX4/snap_cam#32]
In the camera_test.cpp file, the instructions for raw images with the optic flow sensor are contradictory.

Line 50 says do not set preview format.
Line 64 says set preview format. 

I believe line 50 is right; I only got raw streaming working when preview-format was not set.

**Comment by ChristophTobler** [comment]
The camera_test.cpp file is an example from Qualcomm. Please contact Qualcomm directly for questions regarding this file.
