### ISSUE TITLE
where is opencv3 deb package

### ISSUE THREAD

**Issue by parvu** [PX4/snap_cam#6]
couldn.t find opencv3_20160222-1_armhf.deb, but found the work_around:
sudo apt-get install ros-indigo-opencv3
Maybe you can update the readme

**Comment by parvu** [comment]
Also pyside is needed. Please add to dependencies for the computer that runs the calibration :

apt-get install python-pyside

**Comment by LorenzMeier** [comment]
It would be fantastic if you could send a PR

**Comment by parvu** [comment]
Sorry not familiar with initials PR, please explain,
Ah, you mean pull request!
of course, as soon as I will manage to do a camera calibration ...

**Comment by ChristophTobler** [comment]
The .deb file is now linked in the readme and the dependencies are added.
